Traceback (most recent call last):
  File "C:\Users\holly\OneDrive\Desktop\BSUResearch\susie\venv\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\holly\OneDrive\Desktop\BSUResearch\susie\venv\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\holly\OneDrive\Desktop\BSUResearch\susie\venv\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\holly\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\holly\OneDrive\Desktop\BSUResearch\susie\venv\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\holly\OneDrive\Desktop\BSUResearch\susie\venv\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\holly\OneDrive\Desktop\BSUResearch\susie\venv\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
from susie.transit_times import TransitTimes
from susie.ephemeris import Ephemeris
import matplotlib.pyplot as plt
from astropy import coordinates as coords
from astropy import units as u
from astropy import time
import pandoc

------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[2], line 8[0m
[0;32m      6[0m [38;5;28;01mfrom[39;00m [38;5;21;01mastropy[39;00m [38;5;28;01mimport[39;00m units [38;5;28;01mas[39;00m u
[0;32m      7[0m [38;5;28;01mfrom[39;00m [38;5;21;01mastropy[39;00m [38;5;28;01mimport[39;00m time
[1;32m----> 8[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandoc[39;00m

File [1;32m~\OneDrive\Desktop\BSUResearch\susie\venv\Lib\site-packages\pandoc\__init__.py:20[0m
[0;32m     18[0m [38;5;66;03m# Pandoc[39;00m
[0;32m     19[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandoc[39;00m[38;5;21;01m.[39;00m[38;5;21;01mabout[39;00m
[1;32m---> 20[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m [38;5;28;01mimport[39;00m utils
[0;32m     22[0m [38;5;66;03m# Filesystem Helper[39;00m
[0;32m     23[0m [38;5;66;03m# ------------------------------------------------------------------------------[39;00m
[0;32m     24[0m [38;5;28;01mdef[39;00m [38;5;21mrmtree[39m(path):

File [1;32m~\OneDrive\Desktop\BSUResearch\susie\venv\Lib\site-packages\pandoc\utils.py:6[0m
[0;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mwarnings[39;00m
[0;32m      5[0m [38;5;66;03m# Third-Party Libraries[39;00m
[1;32m----> 6[0m [38;5;28;01mimport[39;00m [38;5;21;01mpkg_resources[39;00m
[0;32m      7[0m [38;5;28;01mimport[39;00m [38;5;21;01mply[39;00m[38;5;21;01m.[39;00m[38;5;21;01mlex[39;00m [38;5;28;01mas[39;00m [38;5;21;01mlex[39;00m
[0;32m      8[0m [38;5;28;01mimport[39;00m [38;5;21;01mply[39;00m[38;5;21;01m.[39;00m[38;5;21;01myacc[39;00m [38;5;28;01mas[39;00m [38;5;21;01myacc[39;00m

[1;31mModuleNotFoundError[0m: No module named 'pkg_resources'

