Traceback (most recent call last):
  File "C:\Users\holly\OneDrive\Desktop\BSUResearch\susie\venv\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\holly\OneDrive\Desktop\BSUResearch\susie\venv\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\holly\OneDrive\Desktop\BSUResearch\susie\venv\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\holly\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\holly\OneDrive\Desktop\BSUResearch\susie\venv\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\holly\OneDrive\Desktop\BSUResearch\susie\venv\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\holly\OneDrive\Desktop\BSUResearch\susie\venv\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# STEP 3: Create new transit times object with above data
transit_times_obj1 = TransitTimes('jd', epochs, mid_transit_times, mid_transit_times_err, time_scale='tdb')
# STEP 4 (Optional): To check that the resulting data is correct, you can print each variable and the corresponding data using this command:
# print(vars(transit_times_obj1))
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mTypeError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[5], line 2[0m
[0;32m      1[0m [38;5;66;03m# STEP 3: Create new transit times object with above data[39;00m
[1;32m----> 2[0m transit_times_obj1 [38;5;241m=[39m [43mTransitTimes[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mjd[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mepochs[49m[43m,[49m[43m [49m[43mmid_transit_times[49m[43m,[49m[43m [49m[43mmid_transit_times_err[49m[43m,[49m[43m [49m[43mtime_scale[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mtdb[39;49m[38;5;124;43m'[39;49m[43m)[49m
[0;32m      3[0m [38;5;66;03m# STEP 4 (Optional): To check that the resulting data is correct, you can print each variable and the corresponding data using this command:[39;00m
[0;32m      4[0m [38;5;66;03m# print(vars(transit_times_obj1))[39;00m

File [1;32m~\OneDrive\Desktop\BSUResearch\susie\venv\Lib\site-packages\susie\transit_times.py:66[0m, in [0;36mTransitTimes.__init__[1;34m(self, time_format, epochs, mid_transit_times, mid_transit_times_uncertainties, time_scale, object_ra, object_dec, observatory_lon, observatory_lat)[0m
[0;32m     64[0m     [38;5;28mself[39m[38;5;241m.[39m_validate_times(mid_transit_times_obj, mid_transit_times_uncertainties_obj, (object_ra, object_dec), (observatory_lon, observatory_lat))
[0;32m     65[0m [38;5;66;03m# Call validation function[39;00m
[1;32m---> 66[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_validate[49m[43m([49m[43m)[49m
[0;32m     67[0m [38;5;66;03m# Shift epochs and mid transit times[39;00m
[0;32m     68[0m [38;5;28mself[39m[38;5;241m.[39mepochs [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mepochs [38;5;241m-[39m np[38;5;241m.[39mmin([38;5;28mself[39m[38;5;241m.[39mepochs)

File [1;32m~\OneDrive\Desktop\BSUResearch\susie\venv\Lib\site-packages\susie\transit_times.py:178[0m, in [0;36mTransitTimes._validate[1;34m(self)[0m
[0;32m    176[0m     [38;5;28;01mraise[39;00m [38;5;167;01mTypeError[39;00m([38;5;124m"[39m[38;5;124mThe variable [39m[38;5;124m'[39m[38;5;124mmid_transit_times[39m[38;5;124m'[39m[38;5;124m expected a NumPy array (np.ndarray) but received a different data type[39m[38;5;124m"[39m)
[0;32m    177[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28misinstance[39m([38;5;28mself[39m[38;5;241m.[39mmid_transit_times_uncertainties, np[38;5;241m.[39mndarray):
[1;32m--> 178[0m     [38;5;28;01mraise[39;00m [38;5;167;01mTypeError[39;00m([38;5;124m"[39m[38;5;124mThe variable [39m[38;5;124m'[39m[38;5;124mmid_transit_times_uncertainties[39m[38;5;124m'[39m[38;5;124m expected a NumPy array (np.ndarray) but received a different data type[39m[38;5;124m"[39m)
[0;32m    179[0m [38;5;66;03m# Check that all are same shape[39;00m
[0;32m    180[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mepochs[38;5;241m.[39mshape [38;5;241m!=[39m [38;5;28mself[39m[38;5;241m.[39mmid_transit_times[38;5;241m.[39mshape [38;5;241m!=[39m [38;5;28mself[39m[38;5;241m.[39mmid_transit_times_uncertainties[38;5;241m.[39mshape:

[1;31mTypeError[0m: The variable 'mid_transit_times_uncertainties' expected a NumPy array (np.ndarray) but received a different data type

